# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMapMatMult2 <- function(A, B) {
    .Call(`_GWAS_BAYES_eigenMapMatMult2`, A, B)
}

eigenMapMatMult3 <- function(A, B, C) {
    .Call(`_GWAS_BAYES_eigenMapMatMult3`, A, B, C)
}

